id: IECE42BC2
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-05T19:59:16.521704'
last_modified: '2022-06-05T19:59:16.521716'
parser: null
source_metadata:
  title: Shechen Kongtrul Series
  language: bo
  description: 'Texts by and about Pema Drimé Lekpé Lodrö (zhe chen kong sprul padma
    dri med legs pa''i blo gros, 1901-c.1960), the immediate reincarnation of Jamgön
    Kongtrul Lodrö Thaye at Shechen Monastery:'
  volume:
    f3791:
      title: Prayer to Shechen Kongtrul as Vajrasattva
      base_file: f3791.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
